services:
    webapp:
        image: ${DOCKER_USERNAME:-nativityoftheotokos}/website
        build:
            context: .
            args:
                - PORT=${CONTAINER_PORT:-3000}
            secrets:
                - aws_access_key_id
                - aws_secret_access_key
                - base_url
                - better_auth_secrets
                - better_auth_url
                - database_url
                - google_client_id
                - google_client_secret
                - mailerlite_api_key
                - microsoft_client_id
                - microsoft_client_secret
                - s3_bucket
                - s3_bucket_region
                - yandex_client_id
                - yandex_client_secret
        ports:
            - ${HOST_PORT:-3000}:${CONTAINER_PORT:-3000}
        env_file:
            - .env

secrets:
    aws_access_key_id:
        environment: AWS_ACCESS_KEY_ID
    aws_secret_access_key:
        environment: AWS_SECRET_ACCESS_KEY
    base_url:
        environment: BASE_URL
    better_auth_secrets:
        environment: BETTER_AUTH_SECRETS
    better_auth_url:
        environment: BETTER_AUTH_URL
    database_url:
        environment: DATABASE_URL
    google_client_id:
        environment: GOOGLE_CLIENT_ID
    google_client_secret:
        environment: GOOGLE_CLIENT_SECRET
    mailerlite_api_key:
        environment: MAILERLITE_API_KEY
    microsoft_client_id:
        environment: MICROSOFT_CLIENT_ID
    microsoft_client_secret:
        environment: MICROSOFT_CLIENT_SECRET
    s3_bucket:
        environment: S3_BUCKET
    s3_bucket_region:
        environment: S3_BUCKET_REGION
    yandex_client_id:
        environment: YANDEX_CLIENT_ID
    yandex_client_secret:
        environment: YANDEX_CLIENT_SECRET
